title: Yuliya Klimushina
logo: "/images/logo.jpg?raw=true" 
description: >
  Data scientist
  <br><br>
  Software developer
  <br><br>
  <a href="https://www.linkedin.com/in/yuliya-klimushina/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
#oogle_analytics: UA-000000-0 # your Google Analytics tracking ID here
